---
  el:
    hosts:
      centos-host:
        ansible_connection: docker
        ansible_user: root

  deb:
    hosts:
      ubuntu-host:
        ansible_connection: docker
        ansible_user: root

  local:
    hosts:
      localhost:
        ansible_connection: local
        ansible_user: root
